version: "3.9"
services:
  database:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: buffrs
      POSTGRES_USER: buffrs
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U buffrs"]
      interval: 1s
      timeout: 1s
      retries: 5
    ports:
      - 127.0.0.1:5432:5432
  storage:
    image: minio/minio
    command: server /data
    environment:
      MINIO_ROOT_USER: buffrs
      MINIO_ROOT_PASSWORD: password
      MINIO_DOMAIN: localhost
    ports:
      - 127.0.0.1:9000:9000
  database-migration:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: buffrs
      POSTGRES_USER: buffrs
      POSTGRES_HOST: database
    depends_on:
      database:
        condition: service_healthy
    volumes:
    - "./migrations:/migrations"
    command: ["/bin/bash", "/migrations/up.sh", "/migrations"]
