name: Buffrs CLI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  MINIMUM_LINE_COVERAGE_PERCENT: 35

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup update && rustup component add rustfmt
      - run: cargo fmt --check --all

  # TODO: get registry nixified so we set up an equivalent task in `Nix Buffrs CI`
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: "true"
      - run: rustup update
      - uses: Swatinem/rust-cache@v2
      - name: Install Protoc
        uses: arduino/setup-protoc@v2
      - name: Setup registry
        uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./registry/docker-compose.yml"
      - run: cargo test --workspace
        env:
          RUST_BACKTRACE: 1

  # TODO: get registry nixified so we set up an equivalent task in `Nix Buffrs CI`
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: 'true'
      - run: rustup update
      - run: rustup component add llvm-tools-preview
      - uses: Swatinem/rust-cache@v2
      - run: cargo install cargo-llvm-cov || true
      - name: Install Protoc
        uses: arduino/setup-protoc@v2
      - name: Setup registry
        uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./registry/docker-compose.yml"
      - run: cargo llvm-cov --workspace --fail-under-lines "$MINIMUM_LINE_COVERAGE_PERCENT"

  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - run: cargo install typos-cli@=1.16.26 --locked || true
      - run: typos --exclude /registry/tests/proptest-regressions/
