name: Nix on Mac Buffers CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check_flake_w_nix_on_mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Run `nix flake check`
        run: nix flake check
